- hosts: web
  become: yes
  remote_user: ubuntu
  tasks:
    # - name: Execute the Uptime command over Command module
    #   register: uptimeoutput
    #   command: "uptime"

    # - debug:
    #     var: uptimeoutput.stdout_lines

    - name: "update the apt cache"
      apt:
        update_cache: yes
     

    - name: "Install nginx on ubuntu"
      apt:
        name: ['nginx', 'nginx-common']
        state: present
      
  