version: 2.1

jobs:
  provsion-infrastructure:
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run:
          name: Configure server
          command: |
            aws cloudformation deploy --template-file ec2.yml --stack-name web --region us-east-1
      - run:
          name: Create INV File
          command: |
            yum install -y tar gzip
            aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> inventory.txt
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - inventory.txt

  server-configuration:
      docker:
        - image: python:3.7-alpine3.11

      steps:
        - checkout
        - add_ssh_keys:
            fingerprints: ["ee:ec:8e:5b:55:66:0f:5c:7b:fb:3e:82:ba:87:8f:1c"]
        - run:
            name: Install dependencies
            command: |
              apk add gzip openssh-client ansible
        - attach_workspace:
            # Must be absolute path or relative path from working_directory
            at: .
        - run:
            name: Reading Inventory file
            command: |
              cat inventory.txt
        - run:
            name: Configure Infrastructure
            command: |
              ansible-playbook -i inventory.txt main.yml

              
workflows:
  welcome:
    jobs:
      - provsion-infrastructure
      - server-configuration:
       requires: 
        - provsion-infrastructure
        
      # - testing
         





